# Generated by Django 5.1.7 on 2025-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_conversation_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='agent',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
