# Generated by Django 5.1.7 on 2025-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_conversation_options_conversation_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='endpoint_url',
            field=models.CharField(blank=True, help_text="URL for the agent's chat completion endpoint", max_length=255, null=True),
        ),
    ]
